#pragma once
#ifndef __ENGINE_ENUM_H__
#define __ENGINE_ENUM_H__

enum class 	TRANSFORMSTATEMATRIX { D3DTS_VIEW, D3DTS_PROJECTION, D3DTS_END };
enum class  LEVEL_ID { LEVEL_STATIC, LEVEL_LOGO, LEVEL_STAGE_1, LEVEL_STAGE_2, LEVEL_STAGE_BOSS, LEVEL_END };
enum class  ERootOption { X, Y, Z, XY, XZ, YZ, XYZ, Max };

#endif