#pragma once
#ifndef __CLIENT_ENUM_H__
#define __CLIENT_ENUM_H__
BEGIN(Client)
enum class SCENEID {SCENE_STATIC, SCENE_LOADING, SCENE_LOGO, SCENE_STAGE1, SCENE_TEST_JS, SCENE_TEST_YM, SCENE_TEST_SB, SCENE_END};
enum class GAMEOBJECT 
{
	ENVIRONMENT, 
	PLAYER, 
	WEAPON,
	MONSTER_1H,
	MONSTER_2H,
	MONSTER_SPEAR,
	MONSTER_HEALER,
	MONSTER_SHOOTER,
	MONSTER_ANIMUS,
	MONSTER_CRYSTAL,
	MONSTER_ABERRANT,
	MIDDLE_BOS, 
	BOSS,
	UI_STATIC,
	UI_DYNAMIC,
	EFFECT_EXPLOSION,
	GAMEOBJECT_END
};
END
#endif